# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PicsSmart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PicsSmart
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Alamofire', '~> 4.7'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'SVProgressHUD'

  target 'PicsSmartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PicsSmartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
